spring :
  application :
    name : config-server
#配置git仓库位置
  cloud :
      config :
        server :
          git :
            uri : https://github.com/zhouwdpool/SpringCloud-Learning.git/
#配置仓库路径下的相对搜索位置，可以配置多个
            search-paths : /**
#配置git仓库的用户名
            username : zhouwdpool
#配置git仓库的密码
            password : 892798zwd

server :
  port : 7070
